#!/usr/bin/env node
/** Generates supabase/seed.sql from packages/content/subjects/*.json. Run: npm run content:seed */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(here, "..", "subjects");
const OUT = path.resolve(here, "../../../supabase/seed.sql");
const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const rows = [];
for (const f of fs.readdirSync(DIR).filter((f) => f.endsWith(".json") && f !== "index.json")) {
  const d = JSON.parse(fs.readFileSync(path.join(DIR, f), "utf8"));
  rows.push(
    `(${q(d.id)}, null, ${q(d.content.name)}, ${q(d.stage)}, ${q(d.category)}, true, ${q(JSON.stringify(d.content))}::jsonb)`,
  );
}
const sql = `-- generated by packages/content/scripts/make-seed.mjs — do not edit by hand
insert into public.subjects (slug, owner_id, name, stage, category, is_public, content)
values
${rows.join(",\n")}
on conflict (slug) where owner_id is null do update set name = excluded.name, stage = excluded.stage, category = excluded.category, content = excluded.content, updated_at = now();
`;
fs.writeFileSync(OUT, sql);
console.log("wrote", OUT, rows.length, "subjects");
